App.js
Basic clock that is synced to real time. Tested for iPhone.
=> feat: basic clock

Alarm.js, App.js, package-lock.json, package.json
Basic alarm clock with countdown, time picker, and popup notification.
=> feat: basic alarm

Alarm.js, App.js
Formatted button and fixed countdown timer to display in two digit format.
=> UI Changes

README.md
Added steps for contributing to this repository and additional resources to help with the workflow.
=> Added Contributing and Resources sections

App.js, screens/Alarm.js
Separated project into components and styles
=> Updated file structure

App.js, package-lock.json, package.json, screens/Alarm.js, screens/Home.js, screens/Setting.js
Cleaned up organization of files. Set up a default home page. Implemented react navigation.
=> Set up the settings page and set up a default home page

App.js, components/FooterTab.js, styles.js
This addresses issue #19 
I added a footer tab with three buttons: Clock, Alarm Features, and Settings. The component is outside of the ScrollView so that it remains at the bottom of the user's screen at all times.
=> Add footer tab

App.js, components/FooterTab.js, screens/AlarmFeatures.js, screens/Home.js
Added functionality for "Clock", "Alarm Features", and "Settings" buttons in the navigation footer. Had to add a blank Alarm Features screen as it did not exist already. Also deleted "Go to settings" button.
=> Added logic for footer navigation

README.md
I updated the table of contents, put specific commands in for installation, and added the contact information of the maintainers.
=> Updated Table of Contents and Installation

screens/Alarm.js, screens/Home.js
Minor changes to time picker and to formatting of main alarm page under "clock" tab.
=> commit: alarm time opens correctly in picker

README.md
Added in emojis into the title of the readme and added badges into it too.
=> Edited README  to add badges

package-lock.json, package.json, screens/AlarmCard.js, screens/AlarmClock/AlarmClock.js, screens/AlarmClock/AlarmNameInput.js, screens/AlarmClock/DayPicker.js, screens/AlarmClock/SnoozeSwitch.js, screens/AlarmClock/SoundPicker.js, screens/AlarmClock/TimePickerAndroid.js, screens/AlarmClock/TimePickerIOS.js, screens/Home.js, styles/AlarmStyles.js, styles/styles.js
This outlines the recent updates to the Alarm Clock app I made. 
Please review the updates and provide any feedback
**Selecting Alarm Clock Interface:** The interface for selecting and setting alarms has been moved into its own dedicated folder. This separation of concerns allows for cleaner navigation and component management.
**Alarm Setting Interface:** A new interface for adding alarms has been implemented. It's modeled after the iOS alarm clock
**Manageable Components:** The alarm setting functionality has been broken down into smaller, more manageable components. 
**Dedicated Style Folder:** All styles have been organized into a dedicated folder ./styles/AlarmStyles
**New Card Design:** Alarms are presented with a new card design that includes the alarm time, name, a toggle switch …
=> AlarmClock Page

screens/Alarms.jsx, screens/Home.jsx
This PR should fix issue #47 
One thing I noticed while developing (that interfered with my testing of this feature) is that the time picker in the alarm customization screen doesn't work AT ALL on Android, even currently on main. If this is replicable, I'll open an issue for it.
Also note that this pr was made before dark mode was implemented (#46).
=> Tranferred alarms to alarm screen

components/SettingsToggle.js, screens/Settings.jsx, styles/styles.js
Created a settings component for toggles.
=> Added toggle component for settings

README.md
Description:
This pull request addresses Issue #60 by updating the README.md file. 
The change have been made.
Changes Made:
Updated project installation step from **_cd Alarm-Clock_** to **_cd Alarm-Clock/client_**.
=> FIX : Update README for better documentation [Issue #60]

server/discord/go.mod, server/discord/go.sum, server/discord/main.go
Setup basic discordbot using the discordgo library https://github.com/bwmarrin. To run the bot locally you need to add the BOT_TOKEN to your local env file.
=> Setup basic discord bot

client/screens/Home.tsx
Added confirmation message when delete button is clicked for a time zone clock on the main screen.
=> <added modal confirmation to time zone clock>

client/components/AlarmClock.tsx, client/screens/Alarms.tsx, client/styles/AlarmStyles.ts, client/styles/index.ts
- Redesigned Alarm Clock Page
- Did some code cleaning and refactoring for tidiness
=> Redesigned Alarm Clock Page

.gitignore, server/discord/discord.go, server/discord/discord.md, server/discord/go.mod, server/discord/go.sum, server/discord/main.go, server/discord/webhook.go
Created a simple webhook interaction that posts a test message to a webhook
=> Simple webhook setup and documentation

.github/workflows/linter.yaml, client/contexts/DarkModeContext.js, client/package-lock.json, client/package.json, client/services/sms.js
Automated running linting script on the client. Note, any errors generated by the linter should be fixed before a a PR is sent to main or @kanielv will fix it before merging to main.
=> Inital Linter Setup with Actions

server/cmd/app/main.go, server/internal/api/api.go, server/internal/punishments/discord/webhook/routes.go, server/internal/punishments/discord/webhook/webhook.go, server/internal/types/types.go, server/internal/utils/utils.go
Refactored the backend file structure to make it more readable. Added the discord webhook to the router. Now calling the route /discord/webhook will send a webhook to a test server.
=> refactored code base, created router for discord

README.md
Updated file path for backend in README
=> Updated README to reflect backend changes
